-- doctors
insert into doctor (doctor_id, first_name, last_name) values (1, 'Red', 'Moisey');
insert into doctor (doctor_id, first_name, last_name) values (2, 'Doti', 'Jerdein');
insert into doctor (doctor_id, first_name, last_name) values (3, 'Prescott', 'Josupeit');
insert into doctor (doctor_id, first_name, last_name) values (4, 'Sunshine', 'Lummasana');
insert into doctor (doctor_id, first_name, last_name) values (5, 'Shanie', 'Puddle');
insert into doctor (doctor_id, first_name, last_name) values (6, 'Estrellita', 'Mourbey');
insert into doctor (doctor_id, first_name, last_name) values (7, 'Lisetta', 'Bielfeldt');
insert into doctor (doctor_id, first_name, last_name) values (8, 'Ninetta', 'Engel');
insert into doctor (doctor_id, first_name, last_name) values (9, 'Loraine', 'Mc Meekin');
insert into doctor (doctor_id, first_name, last_name) values (10, 'Cherish', 'Hanes');
insert into doctor (doctor_id, first_name, last_name) values (11, 'Francesco', 'Iglesia');
insert into doctor (doctor_id, first_name, last_name) values (12, 'Sheri', 'Sawers');
insert into doctor (doctor_id, first_name, last_name) values (13, 'Wit', 'Chastelain');
insert into doctor (doctor_id, first_name, last_name) values (14, 'Ralf', 'Muff');
insert into doctor (doctor_id, first_name, last_name) values (15, 'Bevvy', 'D''Alwis');
insert into doctor (doctor_id, first_name, last_name) values (16, 'Nike', 'Lynett');
insert into doctor (doctor_id, first_name, last_name) values (17, 'Barney', 'Coraini');
insert into doctor (doctor_id, first_name, last_name) values (18, 'Carlos', 'Peron');
insert into doctor (doctor_id, first_name, last_name) values (19, 'Eldin', 'Mant');
insert into doctor (doctor_id, first_name, last_name) values (20, 'Craggie', 'Dubber');
insert into doctor (doctor_id, first_name, last_name) values (21, 'Jaymee', 'Sam');
insert into doctor (doctor_id, first_name, last_name) values (22, 'Torre', 'Frier');
insert into doctor (doctor_id, first_name, last_name) values (23, 'Shir', 'Hallford');
insert into doctor (doctor_id, first_name, last_name) values (24, 'Pebrook', 'Hubbold');
insert into doctor (doctor_id, first_name, last_name) values (25, 'Lia', 'Flagg');

-- patient
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (1, 'Tobey', 'Gulleford', 51.23, 1);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (2, 'Lesli', 'Blenkiron', 80.3, 2);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (3, 'Percy', 'Rocca', 83.8, 3);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (4, 'Bowie', 'Warboy', 55.11, 4);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (5, 'Kaitlin', 'MacKellar', 76.71, 5);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (6, 'Virgie', 'Lansdale', 97.1, 6);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (7, 'Nanni', 'Chinge de Hals', 40.78, 7);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (8, 'Kimball', 'Bardwell', 99.64, 8);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (9, 'Paxton', 'Hannaby', 82.0, 9);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (10, 'Zak', 'Goulbourne', 109.46, 10);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (11, 'Arlin', 'Mussington', 63.63, 11);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (12, 'Nils', 'McCard', 58.98, 12);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (13, 'Dari', 'Tschierse', 89.22, 13);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (14, 'Michal', 'Blasi', 70.26, 14);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (15, 'Valry', 'Essex', 71.09, 15);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (16, 'Bank', 'Ebbing', 89.24, 16);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (17, 'Davey', 'Takis', 116.47, 17);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (18, 'Valentina', 'De Santos', 114.45, 18);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (19, 'Marlie', 'Bremner', 47.87, 19);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (20, 'Natala', 'Reinmar', 109.02, 20);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (21, 'Klement', 'Redhills', 107.53, 21);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (22, 'Warden', 'Breslin', 93.01, 22);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (23, 'Krista', 'Vernay', 77.54, 23);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (24, 'Morgen', 'Fayne', 60.5, 24);
insert into patient (patient_id, first_name, last_name, heart_rate, doctor_id) values (25, 'Shanan', 'Siddon', 54.15, 25);
